[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore ./AulaDiser.Proyecto.API/AulaDiser.Proyecto.API.csproj"]

[phases.build]
cmds = ["dotnet publish ./AulaDiser.Proyecto.API/AulaDiser.Proyecto.API.csproj -c Release -o out"]

[start]
cmd = "dotnet ./out/AulaDiser.Proyecto.API.dll"